// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/airking05/go-docker-api-client/models"
)

// ConfigCreateReader is a Reader for the ConfigCreate structure.
type ConfigCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfigCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewConfigCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewConfigCreateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewConfigCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewConfigCreateServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewConfigCreateCreated creates a ConfigCreateCreated with default headers values
func NewConfigCreateCreated() *ConfigCreateCreated {
	return &ConfigCreateCreated{}
}

/*ConfigCreateCreated handles this case with default header values.

no error
*/
type ConfigCreateCreated struct {
	Payload *models.ConfigCreateCreatedBody
}

func (o *ConfigCreateCreated) Error() string {
	return fmt.Sprintf("[POST /configs/create][%d] configCreateCreated  %+v", 201, o.Payload)
}

func (o *ConfigCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigCreateCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigCreateConflict creates a ConfigCreateConflict with default headers values
func NewConfigCreateConflict() *ConfigCreateConflict {
	return &ConfigCreateConflict{}
}

/*ConfigCreateConflict handles this case with default header values.

name conflicts with an existing object
*/
type ConfigCreateConflict struct {
	Payload *models.ErrorResponse
}

func (o *ConfigCreateConflict) Error() string {
	return fmt.Sprintf("[POST /configs/create][%d] configCreateConflict  %+v", 409, o.Payload)
}

func (o *ConfigCreateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigCreateInternalServerError creates a ConfigCreateInternalServerError with default headers values
func NewConfigCreateInternalServerError() *ConfigCreateInternalServerError {
	return &ConfigCreateInternalServerError{}
}

/*ConfigCreateInternalServerError handles this case with default header values.

server error
*/
type ConfigCreateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ConfigCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /configs/create][%d] configCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *ConfigCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigCreateServiceUnavailable creates a ConfigCreateServiceUnavailable with default headers values
func NewConfigCreateServiceUnavailable() *ConfigCreateServiceUnavailable {
	return &ConfigCreateServiceUnavailable{}
}

/*ConfigCreateServiceUnavailable handles this case with default header values.

node is not part of a swarm
*/
type ConfigCreateServiceUnavailable struct {
	Payload *models.ErrorResponse
}

func (o *ConfigCreateServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /configs/create][%d] configCreateServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ConfigCreateServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
