// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/airking05/go-docker-api-client/models"
)

// SystemEventsReader is a Reader for the SystemEvents structure.
type SystemEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSystemEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSystemEventsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewSystemEventsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSystemEventsOK creates a SystemEventsOK with default headers values
func NewSystemEventsOK() *SystemEventsOK {
	return &SystemEventsOK{}
}

/*SystemEventsOK handles this case with default header values.

no error
*/
type SystemEventsOK struct {
	Payload *models.SystemEventsOKBody
}

func (o *SystemEventsOK) Error() string {
	return fmt.Sprintf("[GET /events][%d] systemEventsOK  %+v", 200, o.Payload)
}

func (o *SystemEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SystemEventsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemEventsBadRequest creates a SystemEventsBadRequest with default headers values
func NewSystemEventsBadRequest() *SystemEventsBadRequest {
	return &SystemEventsBadRequest{}
}

/*SystemEventsBadRequest handles this case with default header values.

bad parameter
*/
type SystemEventsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *SystemEventsBadRequest) Error() string {
	return fmt.Sprintf("[GET /events][%d] systemEventsBadRequest  %+v", 400, o.Payload)
}

func (o *SystemEventsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSystemEventsInternalServerError creates a SystemEventsInternalServerError with default headers values
func NewSystemEventsInternalServerError() *SystemEventsInternalServerError {
	return &SystemEventsInternalServerError{}
}

/*SystemEventsInternalServerError handles this case with default header values.

server error
*/
type SystemEventsInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *SystemEventsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /events][%d] systemEventsInternalServerError  %+v", 500, o.Payload)
}

func (o *SystemEventsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
