// Code generated by go-swagger; DO NOT EDIT.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/airking05/accepta/models"
)

// NetworkCreateReader is a Reader for the NetworkCreate structure.
type NetworkCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetworkCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewNetworkCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewNetworkCreateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewNetworkCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewNetworkCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNetworkCreateCreated creates a NetworkCreateCreated with default headers values
func NewNetworkCreateCreated() *NetworkCreateCreated {
	return &NetworkCreateCreated{}
}

/*NetworkCreateCreated handles this case with default header values.

No error
*/
type NetworkCreateCreated struct {
	Payload *models.NetworkCreateCreatedBody
}

func (o *NetworkCreateCreated) Error() string {
	return fmt.Sprintf("[POST /networks/create][%d] networkCreateCreated  %+v", 201, o.Payload)
}

func (o *NetworkCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkCreateCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkCreateForbidden creates a NetworkCreateForbidden with default headers values
func NewNetworkCreateForbidden() *NetworkCreateForbidden {
	return &NetworkCreateForbidden{}
}

/*NetworkCreateForbidden handles this case with default header values.

operation not supported for pre-defined networks
*/
type NetworkCreateForbidden struct {
	Payload *models.ErrorResponse
}

func (o *NetworkCreateForbidden) Error() string {
	return fmt.Sprintf("[POST /networks/create][%d] networkCreateForbidden  %+v", 403, o.Payload)
}

func (o *NetworkCreateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkCreateNotFound creates a NetworkCreateNotFound with default headers values
func NewNetworkCreateNotFound() *NetworkCreateNotFound {
	return &NetworkCreateNotFound{}
}

/*NetworkCreateNotFound handles this case with default header values.

plugin not found
*/
type NetworkCreateNotFound struct {
	Payload *models.ErrorResponse
}

func (o *NetworkCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /networks/create][%d] networkCreateNotFound  %+v", 404, o.Payload)
}

func (o *NetworkCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkCreateInternalServerError creates a NetworkCreateInternalServerError with default headers values
func NewNetworkCreateInternalServerError() *NetworkCreateInternalServerError {
	return &NetworkCreateInternalServerError{}
}

/*NetworkCreateInternalServerError handles this case with default header values.

Server error
*/
type NetworkCreateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *NetworkCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /networks/create][%d] networkCreateInternalServerError  %+v", 500, o.Payload)
}

func (o *NetworkCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
