// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
TaskLogs gets task logs

Get `stdout` and `stderr` logs from a task.

**Note**: This endpoint works only for services with the `json-file` or `journald` logging drivers.

*/
func (a *Client) TaskLogs(params *TaskLogsParams, writer io.Writer) (*TaskLogsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTaskLogsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "TaskLogs",
		Method:             "GET",
		PathPattern:        "/tasks/{id}/logs",
		ProducesMediaTypes: []string{"application/json", "application/vnd.docker.raw-stream"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TaskLogsReader{formats: a.formats, writer: writer},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*TaskLogsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
