// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ConfigCreateParamsBody config create params body
// swagger:model configCreateParamsBody
type ConfigCreateParamsBody struct {
	ConfigSpec
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ConfigCreateParamsBody) UnmarshalJSON(raw []byte) error {

	var aO0 ConfigSpec
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ConfigSpec = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ConfigCreateParamsBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.ConfigSpec)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this config create params body
func (m *ConfigCreateParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.ConfigSpec.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigCreateParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigCreateParamsBody) UnmarshalBinary(b []byte) error {
	var res ConfigCreateParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
