// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerSummaryItemsNetworkSettings A summary of the container's network settings
// swagger:model containerSummaryItemsNetworkSettings
type ContainerSummaryItemsNetworkSettings struct {

	// networks
	Networks ContainerSummaryItemsNetworkSettingsNetworks `json:"Networks,omitempty"`
}

// Validate validates this container summary items network settings
func (m *ContainerSummaryItemsNetworkSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerSummaryItemsNetworkSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerSummaryItemsNetworkSettings) UnmarshalBinary(b []byte) error {
	var res ContainerSummaryItemsNetworkSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
