// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// ContainerCreateParamsBodyAllOf1NetworkingConfigEndpointsConfig A mapping of network name to endpoint configuration for that network.
// swagger:model containerCreateParamsBodyAllOf1NetworkingConfigEndpointsConfig
type ContainerCreateParamsBodyAllOf1NetworkingConfigEndpointsConfig map[string]EndpointSettings

// Validate validates this container create params body all of1 networking config endpoints config
func (m ContainerCreateParamsBodyAllOf1NetworkingConfigEndpointsConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", ContainerCreateParamsBodyAllOf1NetworkingConfigEndpointsConfig(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
