// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerCreateParamsBodyAllOf1NetworkingConfig This container's networking configuration.
// swagger:model containerCreateParamsBodyAllOf1NetworkingConfig
type ContainerCreateParamsBodyAllOf1NetworkingConfig struct {

	// endpoints config
	EndpointsConfig ContainerCreateParamsBodyAllOf1NetworkingConfigEndpointsConfig `json:"EndpointsConfig,omitempty"`
}

// Validate validates this container create params body all of1 networking config
func (m *ContainerCreateParamsBodyAllOf1NetworkingConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerCreateParamsBodyAllOf1NetworkingConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerCreateParamsBodyAllOf1NetworkingConfig) UnmarshalBinary(b []byte) error {
	var res ContainerCreateParamsBodyAllOf1NetworkingConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
