// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerUpdateParamsBodyAllOf1 container update params body all of1
// swagger:model containerUpdateParamsBodyAllOf1
type ContainerUpdateParamsBodyAllOf1 struct {

	// restart policy
	RestartPolicy *RestartPolicy `json:"RestartPolicy,omitempty"`
}

// Validate validates this container update params body all of1
func (m *ContainerUpdateParamsBodyAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRestartPolicy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerUpdateParamsBodyAllOf1) validateRestartPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.RestartPolicy) { // not required
		return nil
	}

	if m.RestartPolicy != nil {

		if err := m.RestartPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("RestartPolicy")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContainerUpdateParamsBodyAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerUpdateParamsBodyAllOf1) UnmarshalBinary(b []byte) error {
	var res ContainerUpdateParamsBodyAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
