// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerArchiveInfoBadRequestBodyAllOf1 container archive info bad request body all of1
// swagger:model containerArchiveInfoBadRequestBodyAllOf1
type ContainerArchiveInfoBadRequestBodyAllOf1 struct {

	// The error message. Either "must specify path parameter" (path cannot be empty) or "not a directory" (path was asserted to be a directory but exists as a file).
	Message string `json:"message,omitempty"`
}

// Validate validates this container archive info bad request body all of1
func (m *ContainerArchiveInfoBadRequestBodyAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerArchiveInfoBadRequestBodyAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerArchiveInfoBadRequestBodyAllOf1) UnmarshalBinary(b []byte) error {
	var res ContainerArchiveInfoBadRequestBodyAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
