// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerArchiveInfoBadRequestBody container archive info bad request body
// swagger:model containerArchiveInfoBadRequestBody
type ContainerArchiveInfoBadRequestBody struct {
	ErrorResponse

	ContainerArchiveInfoBadRequestBodyAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ContainerArchiveInfoBadRequestBody) UnmarshalJSON(raw []byte) error {

	var aO0 ErrorResponse
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ErrorResponse = aO0

	var aO1 ContainerArchiveInfoBadRequestBodyAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ContainerArchiveInfoBadRequestBodyAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ContainerArchiveInfoBadRequestBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.ErrorResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.ContainerArchiveInfoBadRequestBodyAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this container archive info bad request body
func (m *ContainerArchiveInfoBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.ErrorResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.ContainerArchiveInfoBadRequestBodyAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerArchiveInfoBadRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerArchiveInfoBadRequestBody) UnmarshalBinary(b []byte) error {
	var res ContainerArchiveInfoBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
