// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerSummaryItemsHostConfig container summary items host config
// swagger:model containerSummaryItemsHostConfig
type ContainerSummaryItemsHostConfig struct {

	// network mode
	NetworkMode string `json:"NetworkMode,omitempty"`
}

// Validate validates this container summary items host config
func (m *ContainerSummaryItemsHostConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerSummaryItemsHostConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerSummaryItemsHostConfig) UnmarshalBinary(b []byte) error {
	var res ContainerSummaryItemsHostConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
