// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerCreateParamsBody container create params body
// swagger:model containerCreateParamsBody
type ContainerCreateParamsBody struct {
	ContainerConfig

	ContainerCreateParamsBodyAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ContainerCreateParamsBody) UnmarshalJSON(raw []byte) error {

	var aO0 ContainerConfig
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ContainerConfig = aO0

	var aO1 ContainerCreateParamsBodyAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ContainerCreateParamsBodyAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ContainerCreateParamsBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.ContainerConfig)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.ContainerCreateParamsBodyAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this container create params body
func (m *ContainerCreateParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.ContainerConfig.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.ContainerCreateParamsBodyAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerCreateParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerCreateParamsBody) UnmarshalBinary(b []byte) error {
	var res ContainerCreateParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
