// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DistributionInspectOKBodyDescriptor A descriptor struct containing digest, media type, and size
// swagger:model distributionInspectOKBodyDescriptor
type DistributionInspectOKBodyDescriptor struct {

	// digest
	Digest string `json:"Digest,omitempty"`

	// media type
	MediaType string `json:"MediaType,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`

	// urls
	Urls []string `json:"URLs"`
}

// Validate validates this distribution inspect o k body descriptor
func (m *DistributionInspectOKBodyDescriptor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUrls(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DistributionInspectOKBodyDescriptor) validateUrls(formats strfmt.Registry) error {

	if swag.IsZero(m.Urls) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DistributionInspectOKBodyDescriptor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DistributionInspectOKBodyDescriptor) UnmarshalBinary(b []byte) error {
	var res DistributionInspectOKBodyDescriptor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
