// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DistributionInspect distribution inspect
// swagger:model DistributionInspect
type DistributionInspect struct {

	// descriptor
	// Required: true
	Descriptor *DistributionInspectOKBodyDescriptor `json:"Descriptor"`

	// platforms
	// Required: true
	Platforms DistributionInspectOKBodyPlatforms `json:"Platforms"`
}

// Validate validates this distribution inspect
func (m *DistributionInspect) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescriptor(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePlatforms(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DistributionInspect) validateDescriptor(formats strfmt.Registry) error {

	if err := validate.Required("Descriptor", "body", m.Descriptor); err != nil {
		return err
	}

	if m.Descriptor != nil {

		if err := m.Descriptor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Descriptor")
			}
			return err
		}

	}

	return nil
}

func (m *DistributionInspect) validatePlatforms(formats strfmt.Registry) error {

	if err := validate.Required("Platforms", "body", m.Platforms); err != nil {
		return err
	}

	if err := m.Platforms.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Platforms")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DistributionInspect) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DistributionInspect) UnmarshalBinary(b []byte) error {
	var res DistributionInspect
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
