// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EngineDescription EngineDescription provides information about an engine.
// swagger:model EngineDescription
type EngineDescription struct {

	// engine version
	EngineVersion string `json:"EngineVersion,omitempty"`

	// labels
	Labels map[string]string `json:"Labels,omitempty"`

	// plugins
	Plugins EngineDescriptionPlugins `json:"Plugins"`
}

// Validate validates this engine description
func (m *EngineDescription) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *EngineDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineDescription) UnmarshalBinary(b []byte) error {
	var res EngineDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
