// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EngineDescriptionPluginsItems engine description plugins items
// swagger:model engineDescriptionPluginsItems
type EngineDescriptionPluginsItems struct {

	// name
	Name string `json:"Name,omitempty"`

	// type
	Type string `json:"Type,omitempty"`
}

// Validate validates this engine description plugins items
func (m *EngineDescriptionPluginsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *EngineDescriptionPluginsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineDescriptionPluginsItems) UnmarshalBinary(b []byte) error {
	var res EngineDescriptionPluginsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
