// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// HostConfigAllOf1PortBindings A map of exposed container ports and the host port they should map to.
// swagger:model hostConfigAllOf1PortBindings
type HostConfigAllOf1PortBindings map[string]HostConfigAllOf1PortBindingsAdditionalProperties

// Validate validates this host config all of1 port bindings
func (m HostConfigAllOf1PortBindings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", HostConfigAllOf1PortBindings(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
