// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HostConfigAllOf1PortBindingsAdditionalProperties host config all of1 port bindings additional properties
// swagger:model hostConfigAllOf1PortBindingsAdditionalProperties
type HostConfigAllOf1PortBindingsAdditionalProperties struct {

	// The host IP address
	HostIP string `json:"HostIp,omitempty"`

	// The host port number, as a string
	HostPort string `json:"HostPort,omitempty"`
}

// Validate validates this host config all of1 port bindings additional properties
func (m *HostConfigAllOf1PortBindingsAdditionalProperties) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *HostConfigAllOf1PortBindingsAdditionalProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostConfigAllOf1PortBindingsAdditionalProperties) UnmarshalBinary(b []byte) error {
	var res HostConfigAllOf1PortBindingsAdditionalProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
