// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageSearchOKBodyItems image search o k body items
// swagger:model imageSearchOKBodyItems
type ImageSearchOKBodyItems struct {

	// description
	Description string `json:"description,omitempty"`

	// is automated
	IsAutomated bool `json:"is_automated,omitempty"`

	// is official
	IsOfficial bool `json:"is_official,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// star count
	StarCount int64 `json:"star_count,omitempty"`
}

// Validate validates this image search o k body items
func (m *ImageSearchOKBodyItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ImageSearchOKBodyItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageSearchOKBodyItems) UnmarshalBinary(b []byte) error {
	var res ImageSearchOKBodyItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
