// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ImageRootFS image root f s
// swagger:model imageRootFS
type ImageRootFS struct {

	// base layer
	BaseLayer string `json:"BaseLayer,omitempty"`

	// layers
	Layers []string `json:"Layers"`

	// type
	// Required: true
	Type string `json:"Type"`
}

// Validate validates this image root f s
func (m *ImageRootFS) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLayers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImageRootFS) validateLayers(formats strfmt.Registry) error {

	if swag.IsZero(m.Layers) { // not required
		return nil
	}

	return nil
}

func (m *ImageRootFS) validateType(formats strfmt.Registry) error {

	if err := validate.RequiredString("Type", "body", string(m.Type)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImageRootFS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageRootFS) UnmarshalBinary(b []byte) error {
	var res ImageRootFS
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
