// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MountTmpfsOptions Optional configuration for the `tmpfs` type.
// swagger:model mountTmpfsOptions
type MountTmpfsOptions struct {

	// The permission mode for the tmpfs mount in an integer.
	Mode int64 `json:"Mode,omitempty"`

	// The size for the tmpfs mount in bytes.
	SizeBytes int64 `json:"SizeBytes,omitempty"`
}

// Validate validates this mount tmpfs options
func (m *MountTmpfsOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *MountTmpfsOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MountTmpfsOptions) UnmarshalBinary(b []byte) error {
	var res MountTmpfsOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
