// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MountVolumeOptions Optional configuration for the `volume` type.
// swagger:model mountVolumeOptions
type MountVolumeOptions struct {

	// driver config
	DriverConfig *MountVolumeOptionsDriverConfig `json:"DriverConfig,omitempty"`

	// User-defined key/value metadata.
	Labels map[string]string `json:"Labels,omitempty"`

	// Populate volume with data from the target.
	NoCopy *bool `json:"NoCopy,omitempty"`
}

// Validate validates this mount volume options
func (m *MountVolumeOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDriverConfig(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MountVolumeOptions) validateDriverConfig(formats strfmt.Registry) error {

	if swag.IsZero(m.DriverConfig) { // not required
		return nil
	}

	if m.DriverConfig != nil {

		if err := m.DriverConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("DriverConfig")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MountVolumeOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MountVolumeOptions) UnmarshalBinary(b []byte) error {
	var res MountVolumeOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
