// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NetworkCreateCreatedBody NetworkCreateResponse
// swagger:model networkCreateCreatedBody
type NetworkCreateCreatedBody struct {

	// The ID of the created network.
	ID string `json:"Id,omitempty"`

	// warning
	Warning string `json:"Warning,omitempty"`
}

// Validate validates this network create created body
func (m *NetworkCreateCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkCreateCreatedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkCreateCreatedBody) UnmarshalBinary(b []byte) error {
	var res NetworkCreateCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
