// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// NetworkContainers network containers
// swagger:model networkContainers
type NetworkContainers map[string]NetworkContainer

// Validate validates this network containers
func (m NetworkContainers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", NetworkContainers(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
