// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// NetworkSettingsNetworks Information about all networks that the container is connected to.
//
// swagger:model networkSettingsNetworks
type NetworkSettingsNetworks map[string]EndpointSettings

// Validate validates this network settings networks
func (m NetworkSettingsNetworks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", NetworkSettingsNetworks(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
