// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// PluginConfigLinuxDevices plugin config linux devices
// swagger:model pluginConfigLinuxDevices
type PluginConfigLinuxDevices []PluginDevice

// Validate validates this plugin config linux devices
func (m PluginConfigLinuxDevices) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
