// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// PluginSettingsDevices plugin settings devices
// swagger:model pluginSettingsDevices
type PluginSettingsDevices []PluginDevice

// Validate validates this plugin settings devices
func (m PluginSettingsDevices) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
