// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// PluginSettingsMounts plugin settings mounts
// swagger:model pluginSettingsMounts
type PluginSettingsMounts []PluginMount

// Validate validates this plugin settings mounts
func (m PluginSettingsMounts) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
