// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResourceObject An object describing the resources which can be advertised by a node and requested by a task
// swagger:model ResourceObject
type ResourceObject struct {

	// generic resources
	GenericResources GenericResources `json:"GenericResources"`

	// memory bytes
	MemoryBytes int64 `json:"MemoryBytes,omitempty"`

	// nano cpus
	NanoCpus int64 `json:"NanoCPUs,omitempty"`
}

// Validate validates this resource object
func (m *ResourceObject) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceObject) UnmarshalBinary(b []byte) error {
	var res ResourceObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
