// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResourcesBlkioWeightDeviceItems resources blkio weight device items
// swagger:model resourcesBlkioWeightDeviceItems
type ResourcesBlkioWeightDeviceItems struct {

	// path
	Path string `json:"Path,omitempty"`

	// weight
	// Minimum: 0
	Weight *int64 `json:"Weight,omitempty"`
}

// Validate validates this resources blkio weight device items
func (m *ResourcesBlkioWeightDeviceItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWeight(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourcesBlkioWeightDeviceItems) validateWeight(formats strfmt.Registry) error {

	if swag.IsZero(m.Weight) { // not required
		return nil
	}

	if err := validate.MinimumInt("Weight", "body", int64(*m.Weight), 0, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResourcesBlkioWeightDeviceItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourcesBlkioWeightDeviceItems) UnmarshalBinary(b []byte) error {
	var res ResourcesBlkioWeightDeviceItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
