// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResourcesUlimitsItems resources ulimits items
// swagger:model resourcesUlimitsItems
type ResourcesUlimitsItems struct {

	// Hard limit
	Hard int64 `json:"Hard,omitempty"`

	// Name of ulimit
	Name string `json:"Name,omitempty"`

	// Soft limit
	Soft int64 `json:"Soft,omitempty"`
}

// Validate validates this resources ulimits items
func (m *ResourcesUlimitsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ResourcesUlimitsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourcesUlimitsItems) UnmarshalBinary(b []byte) error {
	var res ResourcesUlimitsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
