// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ServiceEndpointVirtualIpsItems service endpoint virtual ips items
// swagger:model serviceEndpointVirtualIpsItems
type ServiceEndpointVirtualIpsItems struct {

	// addr
	Addr string `json:"Addr,omitempty"`

	// network ID
	NetworkID string `json:"NetworkID,omitempty"`
}

// Validate validates this service endpoint virtual ips items
func (m *ServiceEndpointVirtualIpsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceEndpointVirtualIpsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceEndpointVirtualIpsItems) UnmarshalBinary(b []byte) error {
	var res ServiceEndpointVirtualIpsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
