// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ServiceSpecMode Scheduling mode for the service.
// swagger:model serviceSpecMode
type ServiceSpecMode struct {

	// global
	Global interface{} `json:"Global,omitempty"`

	// replicated
	Replicated *ServiceSpecModeReplicated `json:"Replicated,omitempty"`
}

// Validate validates this service spec mode
func (m *ServiceSpecMode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReplicated(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceSpecMode) validateReplicated(formats strfmt.Registry) error {

	if swag.IsZero(m.Replicated) { // not required
		return nil
	}

	if m.Replicated != nil {

		if err := m.Replicated.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Replicated")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceSpecMode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceSpecMode) UnmarshalBinary(b []byte) error {
	var res ServiceSpecMode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
