// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SwarmSpecEncryptionConfig Parameters related to encryption-at-rest.
// swagger:model swarmSpecEncryptionConfig
type SwarmSpecEncryptionConfig struct {

	// If set, generate a key and use it to lock data stored on the managers.
	AutoLockManagers bool `json:"AutoLockManagers,omitempty"`
}

// Validate validates this swarm spec encryption config
func (m *SwarmSpecEncryptionConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SwarmSpecEncryptionConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwarmSpecEncryptionConfig) UnmarshalBinary(b []byte) error {
	var res SwarmSpecEncryptionConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
