// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SwarmSpecOrchestration Orchestration configuration.
// swagger:model swarmSpecOrchestration
type SwarmSpecOrchestration struct {

	// The number of historic tasks to keep per instance or node. If negative, never remove completed or failed tasks.
	TaskHistoryRetentionLimit int64 `json:"TaskHistoryRetentionLimit,omitempty"`
}

// Validate validates this swarm spec orchestration
func (m *SwarmSpecOrchestration) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SwarmSpecOrchestration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwarmSpecOrchestration) UnmarshalBinary(b []byte) error {
	var res SwarmSpecOrchestration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
