// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SystemEventsOKBodyActor system events o k body actor
// swagger:model systemEventsOKBodyActor
type SystemEventsOKBodyActor struct {

	// Various key/value attributes of the object, depending on its type
	Attributes map[string]string `json:"Attributes,omitempty"`

	// The ID of the object emitting the event
	ID string `json:"ID,omitempty"`
}

// Validate validates this system events o k body actor
func (m *SystemEventsOKBodyActor) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SystemEventsOKBodyActor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SystemEventsOKBodyActor) UnmarshalBinary(b []byte) error {
	var res SystemEventsOKBodyActor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
