// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskSpecPlacementPreferencesItemsSpread task spec placement preferences items spread
// swagger:model taskSpecPlacementPreferencesItemsSpread
type TaskSpecPlacementPreferencesItemsSpread struct {

	// label descriptor, such as engine.labels.az
	SpreadDescriptor string `json:"SpreadDescriptor,omitempty"`
}

// Validate validates this task spec placement preferences items spread
func (m *TaskSpecPlacementPreferencesItemsSpread) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TaskSpecPlacementPreferencesItemsSpread) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskSpecPlacementPreferencesItemsSpread) UnmarshalBinary(b []byte) error {
	var res TaskSpecPlacementPreferencesItemsSpread
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
