// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskStatus task status
// swagger:model taskStatus
type TaskStatus struct {

	// container status
	ContainerStatus *TaskStatusContainerStatus `json:"ContainerStatus,omitempty"`

	// err
	Err string `json:"Err,omitempty"`

	// message
	Message string `json:"Message,omitempty"`

	// state
	State TaskState `json:"State,omitempty"`

	// timestamp
	Timestamp string `json:"Timestamp,omitempty"`
}

// Validate validates this task status
func (m *TaskStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContainerStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskStatus) validateContainerStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.ContainerStatus) { // not required
		return nil
	}

	if m.ContainerStatus != nil {

		if err := m.ContainerStatus.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ContainerStatus")
			}
			return err
		}

	}

	return nil
}

func (m *TaskStatus) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("State")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskStatus) UnmarshalBinary(b []byte) error {
	var res TaskStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
