// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskStatusContainerStatus task status container status
// swagger:model taskStatusContainerStatus
type TaskStatusContainerStatus struct {

	// container ID
	ContainerID string `json:"ContainerID,omitempty"`

	// exit code
	ExitCode int64 `json:"ExitCode,omitempty"`

	// p ID
	PID int64 `json:"PID,omitempty"`
}

// Validate validates this task status container status
func (m *TaskStatusContainerStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TaskStatusContainerStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskStatusContainerStatus) UnmarshalBinary(b []byte) error {
	var res TaskStatusContainerStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
