// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskSpecContainerSpecSecretsItems task spec container spec secrets items
// swagger:model taskSpecContainerSpecSecretsItems
type TaskSpecContainerSpecSecretsItems struct {

	// file
	File *TaskSpecContainerSpecSecretsItemsFile `json:"File,omitempty"`

	// SecretID represents the ID of the specific secret that we're referencing.
	SecretID string `json:"SecretID,omitempty"`

	// SecretName is the name of the secret that this references, but this is just provided for
	// lookup/display purposes. The secret in the reference will be identified by its ID.
	//
	SecretName string `json:"SecretName,omitempty"`
}

// Validate validates this task spec container spec secrets items
func (m *TaskSpecContainerSpecSecretsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFile(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskSpecContainerSpecSecretsItems) validateFile(formats strfmt.Registry) error {

	if swag.IsZero(m.File) { // not required
		return nil
	}

	if m.File != nil {

		if err := m.File.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("File")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskSpecContainerSpecSecretsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskSpecContainerSpecSecretsItems) UnmarshalBinary(b []byte) error {
	var res TaskSpecContainerSpecSecretsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
