// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskSpecResources Resource requirements which apply to each individual container created as part of the service.
// swagger:model taskSpecResources
type TaskSpecResources struct {

	// Define resources limits.
	Limits *ResourceObject `json:"Limits,omitempty"`

	// Define resources reservation.
	Reservation *ResourceObject `json:"Reservation,omitempty"`
}

// Validate validates this task spec resources
func (m *TaskSpecResources) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimits(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateReservation(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskSpecResources) validateLimits(formats strfmt.Registry) error {

	if swag.IsZero(m.Limits) { // not required
		return nil
	}

	if m.Limits != nil {

		if err := m.Limits.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Limits")
			}
			return err
		}

	}

	return nil
}

func (m *TaskSpecResources) validateReservation(formats strfmt.Registry) error {

	if swag.IsZero(m.Reservation) { // not required
		return nil
	}

	if m.Reservation != nil {

		if err := m.Reservation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Reservation")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskSpecResources) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskSpecResources) UnmarshalBinary(b []byte) error {
	var res TaskSpecResources
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
