// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskSpecPlacementPreferencesItems task spec placement preferences items
// swagger:model taskSpecPlacementPreferencesItems
type TaskSpecPlacementPreferencesItems struct {

	// spread
	Spread *TaskSpecPlacementPreferencesItemsSpread `json:"Spread,omitempty"`
}

// Validate validates this task spec placement preferences items
func (m *TaskSpecPlacementPreferencesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSpread(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskSpecPlacementPreferencesItems) validateSpread(formats strfmt.Registry) error {

	if swag.IsZero(m.Spread) { // not required
		return nil
	}

	if m.Spread != nil {

		if err := m.Spread.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Spread")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskSpecPlacementPreferencesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskSpecPlacementPreferencesItems) UnmarshalBinary(b []byte) error {
	var res TaskSpecPlacementPreferencesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
