// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskSpecNetworksItems task spec networks items
// swagger:model taskSpecNetworksItems
type TaskSpecNetworksItems struct {

	// aliases
	Aliases []string `json:"Aliases"`

	// target
	Target string `json:"Target,omitempty"`
}

// Validate validates this task spec networks items
func (m *TaskSpecNetworksItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAliases(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskSpecNetworksItems) validateAliases(formats strfmt.Registry) error {

	if swag.IsZero(m.Aliases) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskSpecNetworksItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskSpecNetworksItems) UnmarshalBinary(b []byte) error {
	var res TaskSpecNetworksItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
