// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskSpecPlacement task spec placement
// swagger:model taskSpecPlacement
type TaskSpecPlacement struct {

	// An array of constraints.
	Constraints []string `json:"Constraints"`

	// platforms
	Platforms TaskSpecPlacementPlatforms `json:"Platforms"`

	// preferences
	Preferences TaskSpecPlacementPreferences `json:"Preferences"`
}

// Validate validates this task spec placement
func (m *TaskSpecPlacement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConstraints(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskSpecPlacement) validateConstraints(formats strfmt.Registry) error {

	if swag.IsZero(m.Constraints) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskSpecPlacement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskSpecPlacement) UnmarshalBinary(b []byte) error {
	var res TaskSpecPlacement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
