// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskSpecPluginSpec Invalid when specified with `ContainerSpec`. *(Experimental release only.)*
// swagger:model taskSpecPluginSpec
type TaskSpecPluginSpec struct {

	// Disable the plugin once scheduled.
	Disabled bool `json:"Disabled,omitempty"`

	// The name or 'alias' to use for the plugin.
	Name string `json:"Name,omitempty"`

	// plugin privilege
	PluginPrivilege TaskSpecPluginSpecPluginPrivilege `json:"PluginPrivilege"`

	// The plugin image reference to use.
	Remote string `json:"Remote,omitempty"`
}

// Validate validates this task spec plugin spec
func (m *TaskSpecPluginSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TaskSpecPluginSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskSpecPluginSpec) UnmarshalBinary(b []byte) error {
	var res TaskSpecPluginSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
