// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VolumePruneOKBody volume prune o k body
// swagger:model volumePruneOKBody
type VolumePruneOKBody struct {

	// Disk space reclaimed in bytes
	SpaceReclaimed int64 `json:"SpaceReclaimed,omitempty"`

	// Volumes that were deleted
	VolumesDeleted []string `json:"VolumesDeleted"`
}

// Validate validates this volume prune o k body
func (m *VolumePruneOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVolumesDeleted(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VolumePruneOKBody) validateVolumesDeleted(formats strfmt.Registry) error {

	if swag.IsZero(m.VolumesDeleted) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VolumePruneOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VolumePruneOKBody) UnmarshalBinary(b []byte) error {
	var res VolumePruneOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
